# Site settings
title: Engage with Data Science
email: MaryEllen.Sloane@mtsu.edu
description: > # this means to ignore newlines until "baseurl:"
  Upcoming Date @ MTSU
baseurl:  /engagewithdatascience
url:  https://github.com/mtsu-walkerlib
twitter_username: me_sloane 
github_username:  mesloane 

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


theme: jekyll-theme-minimal
