# Site settings
title: Faculty Technology Showcase at MTSU's Walker Library Septmber 25, 2019
email: MaryEllen.Sloane@mtsu.edu
description: > # this means to ignore newlines until "baseurl:"
  Upcoming Date @ MTSU
baseurl:  /faculty-technology-showcase
url:  https://github.com/mtsu-walkerlib
twitter_username: me_sloane 
github_username:  mesloane 

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


theme: jekyll-theme-minimal
