# Site settings
title: Engage with Data Science
email: MaryEllen.Sloane@mtsu.edu
description: > # this means to ignore newlines until "baseurl:"
  Upcoming Date @ MTSU
baseurl:  /engage-with-data-science
url:  https://github.com/mesloane
twitter_username: me_sloane 
github_username:  me_sloane 

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


theme: jekyll-theme-minimal